# default profile
spring:
  profiles:
    include:
      - httpclient
      - oauth
    active: development
    ## Security
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jwt:
    secret: A11867C8D49A60EF09E35827FACAEE2B55401798D080227000E29E2D1B268B8392D0CC53A7364A9BAA80DB7660F6AAA505842AF1993791FDD5D2989672611BCD
  datasource:
    url: jdbc:mysql://localhost:3306/hot6
    username: root
    password: #password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  #  jpa:
  #
  #    hibernate:
  #      ddl-auto: update
  #    properties:
  #      hibernate:
  #        format_sql=true:
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 822
  tomcat:
    connection-timeout: 30000
    max-threads: 100
    min-spare-threads: 50
    accept-count: 50
    uri-encoding: UTF-8

## AWS Setting
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIATERC7HEQPDZWSRUR
      secret-key: 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
    s3:
      bucket: mats-go
      upload:
        path.review: public/mats
      cdn:
        url: https://mats-go.s3.ap-northeast-2.amazonaws.com


## KAKAO MAP Setting
kakao:
  map:
    api-key: KakaoAK a923dc7dec4381a0f88109db44f594b6
    host: https://dapi.kakao.com
    path.keyword-search: /v2/local/search/keyword.json


## Twitter Api Setting
twitter:
  api-key:
  host: https://api.twitter.com
  path.tweet-search: /1.1/search/tweets.json